/*CREA UN EVENTO DE LA BASE DE DATOS PARA QUE SE ACTUALICEN LAS FACTURAS.
ESTE EVENTO COMIENZA A LAS 00:00:00 DEL DÍA DE CREACIÓN Y SE EJECUTA
PERIÓDICAMENTE CADA DÍA A LAS 00:00:00, LLAMANDO AL PROCEDIMIENTO ALMACENADO
QUE REALIZA DICHAS ACCIONES
 */
SHOW EVENTS;
DROP EVENT actualizar_facturas_ev;

CREATE EVENT IF NOT EXISTS actualizar_facturas_ev
ON SCHEDULE EVERY 1 DAY 
STARTS current_date()
COMMENT 'Actualizar estado de facturas'
DO
CALL actualizar_facturas_proc()


